### ISSUE TITLE
Allow to stop/restart the global connection

### ISSUE THREAD

**Issue by jeluard** [dinchak/node-serialosc#1]
It would be nice to be able to stop/restart the global connections in a running node process. This would be helpful in development scenario where code is reloaded in a live process and probably for tests too.

This requires the ability to have sequences of `start`, `stop` being idempotent.

An option to support that would be to introduce a `stop` method that would `close` underlying socket for `receiver` and `serialoscEmitter` and make sure sockets are created in `start`. Currently sockets are created in `OscReceiver` and `OscEmitter` constructors and never released.

What do you think?

**Comment by dinchak** [comment]
A stop() method has been added in version 0.0.5.  start() can now be called after a stop().

**Comment by jeluard** [comment]
Great thanks!
